### ISSUE TITLE
Explore always seeded to petstore example

### ISSUE THREAD

**Issue by telser** [haskell-servant/servant-swagger-ui#67]
Hi there, I've upgraded a project from stackage lts-13.22 to lts-13.25 which includes updates for servant-swagger-ui from 0.3.2.3.19.3 to 0.3.3.3.22.2.

In doing so it seems that the default "/swagger-ui" page now always has in the explore bar the petstore example json rather than the file from "/swagger.json". Looking through the code it would appear it is related to this hardcoded line: https://github.com/haskell-servant/servant-swagger-ui/blob/fb9c34b888501686ba0cf6076314689f8a2f8c8c/servant-swagger-ui/index.html.tmpl#L52

Am I missing something that would allow me to get back the previous behavior of defaulting to the "swagger.json" definition?

**Comment by phadej** [comment]
Thanks for the report.

Fixed and released: https://hackage.haskell.org/package/servant-swagger-ui-0.3.4.3.22.2

**Comment by telser** [comment]
Awesome thank you!
