### ISSUE TITLE
[BUG] OpenAPI UI doesn't apply Authorization header present in the spec

### ISSUE THREAD

**Issue by coderfromhere** [haskell-servant/servant-swagger-ui#93]
This is a cross-post of https://github.com/biocad/openapi3/issues/29 as I'm not sure which package causes the issue.

below is a sample UI interface that seems to ignore the defined "Authroization" request header and requests fail with expected 401 errors (also see the incomplete curl snippet)

![](https://user-images.githubusercontent.com/59691490/135123614-ed02cc71-b77c-4917-9057-f17d017193e0.png)

A frozen packages snapshot contains:
```
openapi3 ==3.1.0
servant-openapi3 ==2.0.1.2
servant-server ==0.18.2
servant-swagger-ui ==0.3.5.3.47.1
servant-swagger-ui-core ==0.3.5
```

**Comment by maksbotan** [comment]
See https://github.com/biocad/openapi3/issues/29#issuecomment-991932565.
